/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ClienteCTL;
import Controlador.ProductoCTL;
import Modelo.Cliente;
import Modelo.Producto;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author orion
 */
public class Comprar extends javax.swing.JPanel {

    /**
     * Creates new form Comprar
     * @param user
     * @param pc
     */
    public Comprar(Cliente user, Producto pc) {
        initComponents();
        
        this.label_usuario.setText(user.getNombre());
        this.pc = pc;
        this.user = user;
        actualizar(pc);
    }
    // Sacando datos del cliente y del pc
    Cliente user = new Cliente();
    Producto pc = new Producto();
    
    // Metodo para cambiar el panel que se ve en pantalla 
    public void CambiarPanel(JPanel p){
        Panel_base.setLayout(new BorderLayout());

        // Quitar componentes actuales y agregar uno nuevo
        Panel_base.removeAll();
        Panel_base.add(p);
        Panel_base.revalidate(); // Actualiza el diseño
        Panel_base.repaint();    // Redibuja el contenedor
    }
    
    public void actualizar(Producto pc){
        this.label_fabricante.setText(pc.getFabricante());
        this.label_procesador1.setText(pc.getProcesador());
        this.label_grafica.setText(pc.getGrafica());
        this.label_ram.setText(pc.getRam());
        this.label_disco.setText(pc.getDisco());
    }
    
    // Creando objeto controlador de los productos
    ProductoCTL pctl = new ProductoCTL();
    // Creando objeto controlador de cliente
    ClienteCTL clientectl = new ClienteCTL();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_base = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Label_error1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label_usuario = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Label_error2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        label_fabricante = new javax.swing.JLabel();
        label11 = new javax.swing.JLabel();
        label_procesador1 = new javax.swing.JLabel();
        label12 = new javax.swing.JLabel();
        label_grafica = new javax.swing.JLabel();
        label14 = new javax.swing.JLabel();
        label_ram = new javax.swing.JLabel();
        label13 = new javax.swing.JLabel();
        label_disco = new javax.swing.JLabel();
        bt_volver = new javax.swing.JButton();
        bt_comprar = new javax.swing.JButton();

        Panel_base.setBackground(new java.awt.Color(58, 6, 12));
        Panel_base.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(34, 36, 38));

        Label_error1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SoloTodo");

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Conectado como -> ");

        label_usuario.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        label_usuario.setForeground(new java.awt.Color(255, 255, 255));
        label_usuario.setText("null");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label_error1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_usuario)
                .addContainerGap(596, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(Label_error1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(label_usuario)))
                .addGap(22, 22, 22))
        );

        Panel_base.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 60));

        jPanel4.setBackground(new java.awt.Color(34, 36, 38));

        Label_error2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(Label_error2)
                .addContainerGap(993, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(Label_error2)
                .addGap(22, 22, 22))
        );

        Panel_base.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 1000, 40));

        jPanel1.setBackground(new java.awt.Color(34, 36, 38));

        label.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setText("Fabricante:");

        label_fabricante.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        label_fabricante.setForeground(new java.awt.Color(255, 255, 255));
        label_fabricante.setText("null");

        label11.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        label11.setForeground(new java.awt.Color(255, 255, 255));
        label11.setText("Procesador:");

        label_procesador1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        label_procesador1.setForeground(new java.awt.Color(255, 255, 255));
        label_procesador1.setText("null");

        label12.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        label12.setForeground(new java.awt.Color(255, 255, 255));
        label12.setText("Grafica:");

        label_grafica.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        label_grafica.setForeground(new java.awt.Color(255, 255, 255));
        label_grafica.setText("null");

        label14.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        label14.setForeground(new java.awt.Color(255, 255, 255));
        label14.setText("Ram:");

        label_ram.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        label_ram.setForeground(new java.awt.Color(255, 255, 255));
        label_ram.setText("null");

        label13.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        label13.setForeground(new java.awt.Color(255, 255, 255));
        label13.setText("Disco:");

        label_disco.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        label_disco.setForeground(new java.awt.Color(255, 255, 255));
        label_disco.setText("null");

        bt_volver.setBackground(new java.awt.Color(86, 73, 98));
        bt_volver.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        bt_volver.setForeground(new java.awt.Color(255, 255, 255));
        bt_volver.setText("Volver");
        bt_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_volverActionPerformed(evt);
            }
        });

        bt_comprar.setBackground(new java.awt.Color(86, 73, 98));
        bt_comprar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        bt_comprar.setForeground(new java.awt.Color(255, 255, 255));
        bt_comprar.setText("Comprar");
        bt_comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_comprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(label))
                                .addComponent(label11, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(label12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_fabricante)
                            .addComponent(label_grafica)
                            .addComponent(label_procesador1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(label13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_disco))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(label14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_ram)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(bt_volver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addComponent(bt_comprar)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(label_fabricante))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label11)
                    .addComponent(label_procesador1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label12)
                    .addComponent(label_grafica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label14)
                    .addComponent(label_ram))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label13)
                    .addComponent(label_disco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_comprar)
                    .addComponent(bt_volver))
                .addGap(14, 14, 14))
        );

        Panel_base.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 450, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Panel_base, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_comprarActionPerformed
        pctl.eliminar(pc.getId());
        javax.swing.JOptionPane.showMessageDialog(this, "Compra exitosa", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        Tienda T = new Tienda(user);
        CambiarPanel(T);
    }//GEN-LAST:event_bt_comprarActionPerformed

    private void bt_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_volverActionPerformed
        Tienda T = new Tienda(user);
        CambiarPanel(T);
    }//GEN-LAST:event_bt_volverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_error1;
    private javax.swing.JLabel Label_error2;
    private javax.swing.JPanel Panel_base;
    private javax.swing.JButton bt_comprar;
    private javax.swing.JButton bt_volver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel label_disco;
    private javax.swing.JLabel label_fabricante;
    private javax.swing.JLabel label_grafica;
    private javax.swing.JLabel label_procesador1;
    private javax.swing.JLabel label_ram;
    private javax.swing.JLabel label_usuario;
    // End of variables declaration//GEN-END:variables
}
