/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author orion
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        
        Sesion sesion = new Sesion();
        CambiarPanel(sesion);
        
    }
    
    /**
    * Cambia el panel visible en el contenedor principal.
    * 
    * @param panel El nuevo panel que se mostrará en el contenedor principal.
    */
   private void CambiarPanel(JPanel p){
        p.setSize(650, 500);
        p.setLocation(0, 0);
        
        Panel_base.removeAll();
        Panel_base.add(p, BorderLayout.CENTER);
        Panel_base.revalidate();
        Panel_base.repaint();
    }
   
   boolean menu_inicio = true;
   boolean menu_registro = false;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_base = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Label_titulo = new javax.swing.JLabel();
        bt_registro = new javax.swing.JButton();
        bt_ver_usuarios = new javax.swing.JButton();
        bt_delete = new javax.swing.JButton();
        bt_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_base.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout Panel_baseLayout = new javax.swing.GroupLayout(Panel_base);
        Panel_base.setLayout(Panel_baseLayout);
        Panel_baseLayout.setHorizontalGroup(
            Panel_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        Panel_baseLayout.setVerticalGroup(
            Panel_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_base, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 0, 800, 600));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Platinum_3_Rank.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 516, -1, 170));

        Label_titulo.setFont(new java.awt.Font("Roboto Medium", 0, 38)); // NOI18N
        Label_titulo.setText("SoloUsers");
        jPanel1.add(Label_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        bt_registro.setBackground(new java.awt.Color(54, 151, 167));
        bt_registro.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        bt_registro.setForeground(new java.awt.Color(255, 255, 255));
        bt_registro.setText("Registrarse");
        bt_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registroActionPerformed(evt);
            }
        });
        jPanel1.add(bt_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 120, -1));

        bt_ver_usuarios.setBackground(new java.awt.Color(54, 151, 167));
        bt_ver_usuarios.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        bt_ver_usuarios.setForeground(new java.awt.Color(255, 255, 255));
        bt_ver_usuarios.setText("Ver usuarios");
        bt_ver_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ver_usuariosActionPerformed(evt);
            }
        });
        jPanel1.add(bt_ver_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 120, -1));

        bt_delete.setBackground(new java.awt.Color(54, 151, 167));
        bt_delete.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        bt_delete.setForeground(new java.awt.Color(255, 255, 255));
        bt_delete.setText("Eliminar usuarios");
        bt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(bt_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 160, -1));

        bt_salir.setBackground(new java.awt.Color(54, 151, 167));
        bt_salir.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        bt_salir.setForeground(new java.awt.Color(255, 255, 255));
        bt_salir.setText("Salir");
        bt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salirActionPerformed(evt);
            }
        });
        jPanel1.add(bt_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bt_salirActionPerformed

    private void bt_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registroActionPerformed
        Registro registro = new Registro();
        Sesion sesion = new Sesion();
        
        if (menu_inicio == true){
            this.bt_registro.setText("Iniciar sesion");
            
            CambiarPanel(registro);
            menu_inicio = false;
            menu_registro = true;
        }
        else{
            if (menu_registro == true){
                this.bt_registro.setText("Registrarse");
                
                CambiarPanel(sesion);
                menu_inicio = true;
                menu_registro = false;
            }
        }
        
    }//GEN-LAST:event_bt_registroActionPerformed

    private void bt_ver_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ver_usuariosActionPerformed
        Listado sas = new Listado();
        CambiarPanel(sas);
    }//GEN-LAST:event_bt_ver_usuariosActionPerformed

    private void bt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteActionPerformed
        Delete delte = new Delete();
        CambiarPanel(delte);
    }//GEN-LAST:event_bt_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_titulo;
    private javax.swing.JPanel Panel_base;
    private javax.swing.JButton bt_delete;
    private javax.swing.JButton bt_registro;
    private javax.swing.JButton bt_salir;
    private javax.swing.JButton bt_ver_usuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
