/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author orion
 */
public class Inicio_sesion extends javax.swing.JPanel {

    /**
     * Creates new form Inicio_sesion
     */
    public Inicio_sesion() {
        initComponents();
        
        
    }
    
    public Inicio_sesion(Principal framePrincipal) {
        // Acción para cambiar al panel de registro
        bt_registro.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                framePrincipal.CambiarPanel(new Registro());
            }
        });
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_1 = new javax.swing.JPanel();
        Panel_ingresarDatos = new javax.swing.JPanel();
        Label_correo = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        Label_contraseña = new javax.swing.JLabel();
        txt_contraseña = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        bt_inicio = new javax.swing.JButton();
        Panel_secundario = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_txt_1 = new javax.swing.JTextArea();
        bt_registro = new javax.swing.JButton();

        setName(""); // NOI18N

        Panel_1.setBackground(new java.awt.Color(102, 102, 102));
        Panel_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_ingresarDatos.setBackground(new java.awt.Color(243, 243, 243));

        Label_correo.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Label_correo.setText("Correo:");

        txt_correo.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N

        Label_contraseña.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Label_contraseña.setText("Contraseña:");

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel1.setText("Inicio de sesión");

        bt_inicio.setBackground(new java.awt.Color(30, 144, 255));
        bt_inicio.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        bt_inicio.setForeground(new java.awt.Color(255, 255, 255));
        bt_inicio.setText("Iniciar sesión");

        javax.swing.GroupLayout Panel_ingresarDatosLayout = new javax.swing.GroupLayout(Panel_ingresarDatos);
        Panel_ingresarDatos.setLayout(Panel_ingresarDatosLayout);
        Panel_ingresarDatosLayout.setHorizontalGroup(
            Panel_ingresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ingresarDatosLayout.createSequentialGroup()
                .addGroup(Panel_ingresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_ingresarDatosLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(Panel_ingresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Panel_ingresarDatosLayout.createSequentialGroup()
                                .addComponent(Label_contraseña)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_contraseña))
                            .addGroup(Panel_ingresarDatosLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(Label_correo)
                                .addGap(32, 32, 32)
                                .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Panel_ingresarDatosLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1))
                    .addGroup(Panel_ingresarDatosLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(bt_inicio)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        Panel_ingresarDatosLayout.setVerticalGroup(
            Panel_ingresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ingresarDatosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(81, 81, 81)
                .addGroup(Panel_ingresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_correo))
                .addGap(16, 16, 16)
                .addGroup(Panel_ingresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_contraseña)
                    .addComponent(txt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(bt_inicio)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        Panel_1.add(Panel_ingresarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 300, 390));

        Panel_secundario.setBackground(new java.awt.Color(243, 243, 243));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel2.setText("¿No estas registrado?");

        jScrollPane1.setBorder(null);

        area_txt_1.setBackground(new java.awt.Color(243, 243, 243));
        area_txt_1.setColumns(20);
        area_txt_1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        area_txt_1.setRows(5);
        area_txt_1.setText("Create una cuenta en un abrir y cerrar de \nojos, tan solo clickea el boto \"Registrarse\"\ny listo seras dirigido a la pantalla de \nregistro.");
        jScrollPane1.setViewportView(area_txt_1);

        bt_registro.setBackground(new java.awt.Color(30, 144, 255));
        bt_registro.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        bt_registro.setForeground(new java.awt.Color(255, 255, 255));
        bt_registro.setText("Registrarse");
        bt_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_secundarioLayout = new javax.swing.GroupLayout(Panel_secundario);
        Panel_secundario.setLayout(Panel_secundarioLayout);
        Panel_secundarioLayout.setHorizontalGroup(
            Panel_secundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_secundarioLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(Panel_secundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(Panel_secundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_secundarioLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bt_registro)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Panel_secundarioLayout.setVerticalGroup(
            Panel_secundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_secundarioLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
            .addGroup(Panel_secundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_secundarioLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bt_registro)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Panel_1.add(Panel_secundario, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 310, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void bt_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registroActionPerformed

    }//GEN-LAST:event_bt_registroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_contraseña;
    private javax.swing.JLabel Label_correo;
    private javax.swing.JPanel Panel_1;
    private javax.swing.JPanel Panel_ingresarDatos;
    private javax.swing.JPanel Panel_secundario;
    private javax.swing.JTextArea area_txt_1;
    private javax.swing.JButton bt_inicio;
    private javax.swing.JButton bt_registro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField txt_contraseña;
    private javax.swing.JTextField txt_correo;
    // End of variables declaration//GEN-END:variables

    

}
