/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author orion
 */
public class Registro extends javax.swing.JPanel {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_1 = new javax.swing.JPanel();
        Panel_ingresarDatos = new javax.swing.JPanel();
        Label_correo = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        Label_contraseña = new javax.swing.JLabel();
        txt_contraseña = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        Label_nombre = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        bt_registro = new javax.swing.JButton();

        Panel_1.setBackground(new java.awt.Color(102, 102, 102));
        Panel_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_ingresarDatos.setBackground(new java.awt.Color(243, 243, 243));

        Label_correo.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Label_correo.setText("Correo:");

        txt_correo.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N

        Label_contraseña.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Label_contraseña.setText("Contraseña:");

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel1.setText("Registrar cuenta");

        Label_nombre.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Label_nombre.setText("Nombre:");

        txt_nombre.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N

        bt_registro.setBackground(new java.awt.Color(30, 144, 255));
        bt_registro.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        bt_registro.setForeground(new java.awt.Color(255, 255, 255));
        bt_registro.setText("Registrarse");

        javax.swing.GroupLayout Panel_ingresarDatosLayout = new javax.swing.GroupLayout(Panel_ingresarDatos);
        Panel_ingresarDatos.setLayout(Panel_ingresarDatosLayout);
        Panel_ingresarDatosLayout.setHorizontalGroup(
            Panel_ingresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ingresarDatosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(Panel_ingresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ingresarDatosLayout.createSequentialGroup()
                        .addComponent(Label_contraseña)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_ingresarDatosLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(Panel_ingresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Panel_ingresarDatosLayout.createSequentialGroup()
                                .addComponent(Label_nombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel_ingresarDatosLayout.createSequentialGroup()
                                .addComponent(Label_correo)
                                .addGap(32, 32, 32)
                                .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ingresarDatosLayout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addGroup(Panel_ingresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ingresarDatosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(157, 157, 157))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ingresarDatosLayout.createSequentialGroup()
                        .addComponent(bt_registro)
                        .addGap(190, 190, 190))))
        );
        Panel_ingresarDatosLayout.setVerticalGroup(
            Panel_ingresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ingresarDatosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(79, 79, 79)
                .addGroup(Panel_ingresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_ingresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_correo))
                .addGap(16, 16, 16)
                .addGroup(Panel_ingresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_contraseña)
                    .addComponent(txt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(bt_registro)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        Panel_1.add(Panel_ingresarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 490, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_contraseña;
    private javax.swing.JLabel Label_correo;
    private javax.swing.JLabel Label_nombre;
    private javax.swing.JPanel Panel_1;
    private javax.swing.JPanel Panel_ingresarDatos;
    private javax.swing.JButton bt_registro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField txt_contraseña;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
