/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ClienteCTL;
import Modelo.Cliente;
import Modelo.Producto;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author orion
 */
public class VerComponentes extends javax.swing.JFrame {

    /**
     * Creates new form VerComponentes
     */
    public VerComponentes(Producto pc) {
        initComponents();
        actualizar(pc);
        
    }
    
    public void actualizar(Producto pc){
        this.label_fabricante.setText(pc.getFabricante());
        this.label_procesador1.setText(pc.getProcesador());
        this.label_grafica.setText(pc.getGrafica());
        this.label_ram.setText(pc.getRam());
        this.label_disco.setText(pc.getDisco());
        this.label_precio.setText(""+pc.getPrecio());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_base2 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        label12 = new javax.swing.JLabel();
        label11 = new javax.swing.JLabel();
        label13 = new javax.swing.JLabel();
        label_fabricante = new javax.swing.JLabel();
        label_grafica = new javax.swing.JLabel();
        label_procesador1 = new javax.swing.JLabel();
        label_disco = new javax.swing.JLabel();
        label14 = new javax.swing.JLabel();
        label_ram = new javax.swing.JLabel();
        label_precio = new javax.swing.JLabel();
        label15 = new javax.swing.JLabel();
        bt_cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Panel_base2.setBackground(new java.awt.Color(58, 6, 12));
        Panel_base2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(34, 36, 38));

        label.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setText("Fabricante:");

        label12.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        label12.setForeground(new java.awt.Color(255, 255, 255));
        label12.setText("Grafica:");

        label11.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        label11.setForeground(new java.awt.Color(255, 255, 255));
        label11.setText("Procesador:");

        label13.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        label13.setForeground(new java.awt.Color(255, 255, 255));
        label13.setText("Disco:");

        label_fabricante.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        label_fabricante.setForeground(new java.awt.Color(255, 255, 255));
        label_fabricante.setText("null");

        label_grafica.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        label_grafica.setForeground(new java.awt.Color(255, 255, 255));
        label_grafica.setText("null");

        label_procesador1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        label_procesador1.setForeground(new java.awt.Color(255, 255, 255));
        label_procesador1.setText("null");

        label_disco.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        label_disco.setForeground(new java.awt.Color(255, 255, 255));
        label_disco.setText("null");

        label14.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        label14.setForeground(new java.awt.Color(255, 255, 255));
        label14.setText("Ram:");

        label_ram.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        label_ram.setForeground(new java.awt.Color(255, 255, 255));
        label_ram.setText("null");

        label_precio.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        label_precio.setForeground(new java.awt.Color(255, 255, 255));
        label_precio.setText("null");

        label15.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        label15.setForeground(new java.awt.Color(255, 255, 255));
        label15.setText("Precio:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(label))
                                .addComponent(label11, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(label12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_fabricante)
                            .addComponent(label_grafica)
                            .addComponent(label_procesador1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(label13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_disco))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(label14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_ram)))))
                .addContainerGap(180, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label15)
                .addGap(18, 18, 18)
                .addComponent(label_precio)
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(label_fabricante))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label11)
                    .addComponent(label_procesador1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label12)
                    .addComponent(label_grafica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label14)
                    .addComponent(label_ram))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label13)
                    .addComponent(label_disco))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_precio)
                    .addComponent(label15))
                .addGap(423, 423, 423))
        );

        Panel_base2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 350, 230));

        bt_cerrar.setBackground(new java.awt.Color(86, 73, 98));
        bt_cerrar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        bt_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bt_cerrar.setText("Cerrar");
        bt_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cerrarActionPerformed(evt);
            }
        });
        Panel_base2.add(bt_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Panel_base2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 6, Short.MAX_VALUE)
                    .addComponent(Panel_base2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cerrarActionPerformed
        dispose();
    }//GEN-LAST:event_bt_cerrarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VerComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VerComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VerComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VerComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
////        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new VerComponentes().setVisible(true);
////            }
////        });
////    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_base2;
    private javax.swing.JButton bt_cerrar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel label15;
    private javax.swing.JLabel label_disco;
    private javax.swing.JLabel label_fabricante;
    private javax.swing.JLabel label_grafica;
    private javax.swing.JLabel label_precio;
    private javax.swing.JLabel label_procesador1;
    private javax.swing.JLabel label_ram;
    // End of variables declaration//GEN-END:variables
}
